version: '3.7'
services:
  postgres:
    image: postgres:14.9
    container_name: postgres-dvdRental
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
